version: '3.8'
services:
  odatabookstore:
    build:
      context: ./ODataBookStore
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  odatabookstorewebclient:
    build:
      context: ./ODataBookStoreWebClient
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - odatabookstore
