version: '3.8'
services:
  odatabookstore:
    build:
      context: .
      dockerfile: ODataBookStore/Dockerfile
      target: final
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  odatabookstorewebclient:
    build:
      context: .
      dockerfile: ODataBookStoreWebClient/Dockerfile
      target: final
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - odatabookstore
